Make `Input::new` robust against malicious `AsRef` implementations
rust-lang/regex pull request #1154
Opened 2024-01-19 21:16 UTC by SkiFire13

Currently `Input::new` calls `haystack.as_ref()` twice, once to get the actual `haystack` slice and the second time to get its length. It makes the assumption that the second call will return the same slice, but malicious implementations of `AsRef` can return different slices and thus different lengths. This is important because there's `unsafe` code relying on the `Input`'s span being inbounds with respect to the `haystack`, but if the second call to `.as_ref()` returns a bigger slice this won't be true.

For example, this snippet causes MIRI to report UB on an unchecked slice access in `find_fwd_imp` (though it will also panic sometime later when run normally, but at that point the UB already happened):

```rs
use regex_automata::{Input, meta::{Builder, Config}};
use std::cell::Cell;

struct Bad(Cell<bool>);

impl AsRef<[u8]> for Bad {
    fn as_ref(&self) -> &[u8] {
        if self.0.replace(false) {
            &[]
        } else {
            &[0; 1000]
        }
    }
}

let bad = Bad(Cell::new(true));
let input = Input::new(&bad);
let regex = Builder::new()
    .configure(Config::new().auto_prefilter(false)) // Not setting this causes some checked access to occur before the unchecked ones, avoiding the UB
    .build("a+")
    .unwrap();
regex.find(input);
```

The proposed fix is to just call `.as_ref()` once and use the length of the returned slice as the span's end value. A regression test has also been added.

2024-01-20 13:20 UTC, BurntSushi requested changes
Nice fix! Out of curiosity, how did you find this?

I think this overall looks good, but I'd like to find a word other than "malicious." The issue here really isn't "malicious" per se, because the threat model here doesn't really involve some bad actor doing something sneaky (if a bad actor can insert a malicious `AsRef` impl, then they can do a whole bunch of other stuff without need for such things). Perhaps "guarding against incorrect `AsRef` impls" is a better way to phrase it.

2024-01-20 15:42 UTC, SkiFire13 commented
> Nice fix! Out of curiosity, how did you find this?

I happened to gave a quick look at `Input::new`'s source code and the two calls to `.as_ref()` reminded me of rust-lang/rust#80335 so I quickly checked if there was `unsafe` code relying on the span's end and there was.

2024-01-21 13:15 UTC, BurntSushi approved these changes

2024-01-21 14:07 UTC, merged

2024-01-21 14:09 UTC, BurntSushi commented
This PR is on crates.io in `regex 1.10.3`.