doc: add a doctest to demonstrate a separately-compiled regex set
rust-lang/regex pull request #861
Opened 2022-05-20 09:49 UTC by cosmicexplorer

It took me a while to understand the recommendation for how to get `Match` objects when using a `RegexSet`. I tried to rewrite that part and added a doctest to make it super clear!

2022-05-20 18:00 UTC, BurntSushi requested changes
Thanks! The substance looks good, but there are some details that I'd like to see fixed before merging.

Also, I do think these restrictions have a very good chance of being lifted in the future with new APIs on `RegexSet`. But it's still a long ways off so I agree it's worth clarifying the docs here for now.

2022-05-20 18:01 UTC, BurntSushi commented on src/re_set.rs
> +/// let regexen: Vec<_> = patterns.iter().map(|pat| Regex::new(pat).unwrap()).collect();
Errmm, yeah, not `set`. Whoops. `regexes` then. :)

2022-05-20 18:02 UTC, BurntSushi commented
Also, please squash down to one commit.

2022-05-31 03:06 UTC, cosmicexplorer commented on src/re_set.rs
> +/// let regexen: Vec<_> = patterns.iter().map(|pat| Regex::new(pat).unwrap()).collect();
Done! Thanks!

2022-05-31 03:07 UTC, cosmicexplorer commented on src/re_set.rs
> +/// patterns:
Done, for both!

2022-05-31 03:07 UTC, cosmicexplorer commented on src/re_set.rs
> +/// assert_eq!(["foo", "bar"].as_ref(), &matches);
I really appreciate this in-depth description! Thanks so much for clarifying!

2022-05-31 03:10 UTC, cosmicexplorer commented on src/re_set.rs
> +/// let regexen: Vec<_> = patterns.iter().map(|pat| Regex::new(pat).unwrap()).collect();
`regexen` is terminology used in a few places in the emacs manual to collectively refer to multiple regex patterns.

2022-05-31 03:10 UTC, cosmicexplorer commented on src/re_set.rs
> +/// ```
Thank you! Super easy!

2022-05-31 03:11 UTC, cosmicexplorer commented on src/re_set.rs
> +/// independently compiled patterns:
Awesome!

2022-05-31 03:12 UTC, cosmicexplorer commented on src/re_set.rs
> +/// # use regex::{Regex, RegexSet};
Ok, I have uncommented it! However, it looks like all the other examples in this *file* (`re_set.rs`) have this `use` statement commented out -- should I fix those, too? e.g. https://github.com/rust-lang/regex/blob/9aef5b1edc2a436244b936db53a03ed6d720e87e/src/re_set.rs#L425

2022-05-31 03:17 UTC, cosmicexplorer commented
@BurntSushi:
> Also, I do think these restrictions have a very good chance of being lifted in the future with new APIs on RegexSet

That's awesome to hear!! Turned on notifs for this repo!

2022-06-22 22:19 UTC, cosmicexplorer commented
Ping!

2022-07-05 17:03 UTC, BurntSushi approved these changes

2022-07-05 17:04 UTC, merged