Added `participating_captures_len`
rust-lang/regex pull request #908
Opened 2022-09-24 15:17 UTC by orlp

Long overdue, but this is the first step towards adding https://github.com/rust-lang/regex/issues/824, as greenlit by @BurntSushi.

This new method of `Regex` returns the number of capture groups that will be filled during a successful match, or `None` if this can't be statically determined during `Regex` compile time.

2022-09-24 17:04 UTC, BurntSushi requested changes
Thanks!

One particularly unfortunate thing about timing here is that I have a [WIP branch](https://github.com/rust-lang/regex/compare/master...ag/regex-automata) that refactors quite a bit of code that this PR also touches. In particular, `HirInfo` is dropped in favor of a new `Properties` type, and the `Repetition` HIR definition is simplified considerably. So pretty much all of the code in this PR will need to be ported over to that branch. The other unfortunate thing is that I have no timeline as to when that branch will get pulled into `master`. Maybe by the end of the year?

We could get this merged now, but the merge conflicts are going to be brutal enough that it would be easier to just port the patch by hand.

I can probably do the porting for you, but commit authorship won't be preserved.

Otherwise, there are a few changes here that I think need to be made. I'm also not entirely happy with the name `participating_captures_len`. I'll think about that.

2022-09-24 17:18 UTC, orlp commented
> We could get this merged now, but the merge conflicts are going to be brutal enough that it would be easier to just port the patch by hand.

We should probably coordinate a bit then before I make any further changes. I could re-do the patch on the WIP branch myself if it is in a compiling state and the structure is roughly the same. I don't really see the value of putting it into `master` if it's going to be replaced soon anyway. Especially since you said this:

> Could you back out the public API changes to regex please? I'm fine adding this to regex-syntax, but I'm less sure about it being in the regex API.

If `participating_captures_len` is not accessible externally from the `Regex` object itself, there is no point to this PR other than as preparatory work for the inclusion of `extract` in `regex` itself. If I convinced you about this, then that's great and I'm happy to help where possible. But if you are still on the fence about `extract` then adding `participating_captures_len` to `regex-syntax` does nothing for making `extract` possible as an extension trait.

2022-09-24 17:27 UTC, BurntSushi commented
> I could re-do the patch on the WIP branch myself if it is in a compiling state and the structure is roughly the same.

It is and the overall structure is indeed the same.

> I don't really see the value of putting it into master though if it's going to be replaced soon anyway.

Aye. Just to set expectations here, this branch is the culmination of #656, which I have been working on for years. While it might get merged by the end of this year, I can't make any promises.

> If `participating_captures_len` is not accessible externally from the `Regex` object itself, there is no point to this PR other than as preparatory work for the inclusion of `extract` in `regex` itself. If I convinced you about this, then that's great and I'm happy to help where possible. But if you are still on the fence about `extract` then adding `participating_captures_len` to `regex-syntax` does nothing for making `extract` possible as an extension trait.

Ah hmmm, yes, I see. You could still do it in another crate, but it would require a lot more ceremony. Namely, a wrapper type around `Regex` that parsed the pattern a second time to figure out the `participating_captures_len` property. That's not so good.

OK, I'm fine with adding this to the `regex` API, but it should come with at least some doc examples. One example might even be the `extract` implementation itself, since it's so simple.

Thinking about alternative names too... Ideas:

* `fixed_captures_len`
* `static_captures_len`

Other ideas?

2022-09-24 18:26 UTC, orlp commented
For the bikeshedding, other options might be `unconditional_captures_len`, `exact_captures_len`, `guaranteed_captures_len`, `proven_captures_len`.

> Aye. Just to set expectations here, this branch is the culmination of https://github.com/rust-lang/regex/issues/656, which I have been working on for years. While it might get merged by the end of this year, I can't make any promises.
> ...
> OK, I'm fine with adding this to the regex API, but it should come with at least some doc examples. One example might even be the extract implementation itself, since it's so simple.

Alright then, since you're okay with it going public on `Regex` I think I will (for now) simply make your requested changes for the `master` branch, so that hopefully in the next release of `regex` it's possible to write the checked extension trait and have it be immediately useful.

> OK, I'm fine with adding this to the regex API, but it should come with at least some doc examples. One example might even be the extract implementation itself, since it's so simple.

I think while simple it might be a bit too big for an example. I'll make sure to add some examples though.

2022-09-24 18:31 UTC, BurntSushi commented
> Alright then, since you're okay with it going public on `Regex` I think I will (for now) simply make your requested changes for the `master` branch, so that hopefully in the next release of `regex` it's possible to write the checked extension trait and have it be immediately useful.

Sorry, to be clear, I do not really want to merge this into master. As I said above, the merge conflicts against my WIP branch will be brutal.

2022-09-24 18:51 UTC, orlp commented
> > Alright then, since you're okay with it going public on `Regex` I think I will (for now) simply make your requested changes for the `master` branch, so that hopefully in the next release of `regex` it's possible to write the checked extension trait and have it be immediately useful.
> 
> Sorry, to be clear, I do not really want to merge this into master. As I said above, the merge conflicts against my WIP branch will be brutal.

Ah alright. I'll work on a pull request on the other branch then.

2023-03-04 18:40 UTC, BurntSushi commented
OK, I've ported this patch to the new branch. And I've put it in the `regex` API as well. Here is that method and its docs:

```rust
    /// Returns the total number of explicit capturing groups that appear in
    /// every possible match.
    ///
    /// If the number of capture groups can vary depending on the match, then
    /// this returns `None`. That is, a value is only returned when the number
    /// of matching groups is invariant or "static."
    ///
    /// Note that like [`Regex::captures_len`], this **does** include the
    /// implicit capturing group corresponding to the entire match. Therefore,
    /// when a non-None value is returned, it is guaranteed to be at least `1`.
    /// Stated differently, a return value of `Some(0)` is impossible.
    ///
    /// # Example
    ///
    /// This shows a few cases where a static number of capture groups is
    /// available and a few cases where it is not.
    ///
    /// ```
    /// use regex::Regex;
    ///
    /// let len = |pattern| {
    ///     Regex::new(pattern).map(|re| re.static_captures_len())
    /// };
    ///
    /// assert_eq!(Some(1), len("a")?);
    /// assert_eq!(Some(2), len("(a)")?);
    /// assert_eq!(Some(2), len("(a)|(b)")?);
    /// assert_eq!(Some(3), len("(a)(b)|(c)(d)")?);
    /// assert_eq!(None, len("(a)|b")?);
    /// assert_eq!(None, len("a|(b)")?);
    /// assert_eq!(None, len("(b)*")?);
    /// assert_eq!(Some(2), len("(b)+")?);
    ///
    /// # Ok::<(), Box<dyn std::error::Error>>(())
    /// ```
    #[inline]
    pub fn static_captures_len(&self) -> Option<usize> { ... }
```

In particular, there is one crucial difference here (other than the name): for a `Some` value, the length is **always at least `1`.** This makes it consistent with the value returned by `captures_len`.

2023-03-04 20:44 UTC, orlp commented
Seems fair enough to me 👍

2023-03-04 20:49 UTC, BurntSushi commented
@orlp Also, thank you for the great tests! I was able to copy them over pretty easily, and it looks like they have good coverage. Overall it was pretty easy to port over. The logic was all roughly the same!

2023-04-17 19:42 UTC, closed without merging